# 何为错误？

​		在Rust中的错误分为**可恢复**和**不可恢复两类**。

​		1⃣️ Rust中使用`Result`枚举来处理可恢复错误，`Result`枚举有两个值，分别为：Ok和Err。

​    			在成功情况下，返回Ok枚举，其中包含一个成功值。

​    			在失败情况下，返回Err枚举，其中包含错误对象。

​		2⃣️ Rust中使用panic宏来处理不可恢复错误。在`Result`上可以调用`unwrap`或者`expect`来做不可恢复处理。

​		3⃣️ 在处理panic情况下，可以使用环境变量RUST_BACKTRACE=1来输出调用栈，方便调试。

# 异常处理的使用场景

​		1⃣️ 对于大部分可恢复的错误处理场景，应该使用`Result`枚举和错误传播，这样做有如下好处：

a.防止程序崩溃

b.让调用方决策如何进行进一步的处理

​		2⃣️ 2.在极少数情况下，可以考虑使用panic宏，主要有如下场景：

a.不可恢复的错误，必须非正常退出的程序

b.对于样例代码，使用`unwrap`或者`expect`简化代码

c.对于原型代码，不想花费太多的时间在详细的错误处理上（当原型代码初步通过验证可能发展为生产代码时，在优化错误处理）

d.对于测试代码，想要快速失败

# [案例](./src/main.rs)

